apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal
  name: api-update-vendor-invoice-reim
  labels:
    cloud.googleapis.com/location: northamerica-northeast1
spec:
  template:
    spec:
      containers:
        - image: app
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
